cxx_binary(
  name = 'auto_cpu_timer_example',
  srcs = [
    'auto_cpu_timer_example.cpp',
  ],
  deps = [
    '//:timer',
  ],
)

cxx_binary(
  name = 'timex',
  srcs = [
    'timex.cpp',
  ],
  deps = [
    '//:timer',
  ],
)
